version: '3.9'

services:
  scraping_service:
    image: sleepygiantpandabear/scraping_service:latest
    container_name: scraping_service
    ports:
      - 8080:1323 
    restart: unless-stopped
    networks:
      - scraping_service_net
    environment:
           MONGODB_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - scraping_service_mongodb_vol:/data/db
    restart: unless-stopped
    networks:
      - scraping_service_net

volumes:
  scraping_service_mongodb_vol:

networks:
  scraping_service_net:
    driver: bridge
